### ISSUE TITLE
Make the app borderless.

### ISSUE THREAD

**Issue by azzsal** [CSCI-2108-Final-Projects/Readile#7]
- [x] Disable the default stage outline.
- [x] Create custom minimize and close buttons.

**Alternative:**
- Create a custom Title Bar that contains the custom minimize and close buttons.

**Comment by ZakiKurdya** [comment]
Check this out:
https://medium.com/@keeptoo/making-a-borderless-javafx-window-movable-f7855eb33a51

And use **ToolBar** to add custom minimize and close buttons

**Comment by azzsal** [comment]
> And use **ToolBar** to add custom minimize and close buttons

I'd be really grateful if you could add it to the prototype.

**Comment by ZakiKurdya** [comment]
> I'd be really grateful if you could add it to the prototype.

Sure, I'll add it soon
